# Generated by Django 4.0.4 on 2022-04-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_rename_user_skill_set_userskillset'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('opening', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer')),
            ],
        ),
    ]
