# Generated by Django 4.0.4 on 2022-04-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.newuser',),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.newuser',),
        ),
        migrations.AddField(
            model_name='newuser',
            name='type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('EMPLOYER', 'Employer')], default='EMPLOYEE', max_length=100, verbose_name='Types'),
        ),
    ]
