# Generated by Django 4.0.4 on 2022-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employerprofile_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
