# Generated by Django 4.0.4 on 2022-04-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_skillset_user_skill_set_institution_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_skill_set',
            new_name='UserSkillSet',
        ),
    ]
