# Generated by Django 4.0.4 on 2022-04-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_user_skill_set_userskillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.employee'),
        ),
    ]
