# Generated by Django 4.0.4 on 2022-04-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_employeeprofile_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
    ]
